apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuprojeto-database-deployment
  labels:
    app: meuprojeto-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meuprojeto-database
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: meuprojeto-database
    spec:
      containers:
        - name: 'meuprojeto-database'
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meuprojeto-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: meuprojeto-secret
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: meuprojeto-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meuprojeto-secret
                  key: DB_PASSWORD
