apiVersion: v1
kind: ConfigMap
metadata:
  name: meuprojeto-config
data:
  APP_NAME: "Meu Projeto"
  APP_ENV: local
  APP_DEBUG: "true"
  APP_TIMEZONE: America/Fortaleza
  APP_URL: "http://localhost:8080"
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
